-- CAU 1 --
CREATE DATABASE QLHANG
GO
USE thigiuaky
GO

CREATE TABLE VATTU(
    MAVT varchar(5) PRIMARY KEY, 
    TENVT nvarchar(50),
    DVTINH nvarchar(50),
    SLCON INT
);

CREATE TABLE HDBAN(
    MAHD varchar(5) PRIMARY KEY, 
    NGAYXUAT DATE,
    HOTENKHACH nvarchar(50)
);

CREATE TABLE HANGXUAT(
    MAHD varchar(5),
    MAVT varchar(5),
    DONGIA INT,
    SLBAN INT,
    CONSTRAINT HANGXUAT_PK PRIMARY KEY (MAHD, MAVT)
);

ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_HDBAN
FOREIGN KEY (MAHD) REFERENCES HDBAN (MAHD);
ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_VATTU
FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT);

INSERT INTO VATTU VALUES
('VT01', N'ĐÁ HOA CƯƠNG', 'VIEN', 1000),
('VT02', 'XI-MĂNG', 'BAO', 3000);

INSERT INTO HDBAN VALUES
('HD01', '2022-12-14', N'HUỲNH TẤN ĐẠT '),
('HD02', '2022-12-15', N'NGUYỄN VĂN A ');

INSERT INTO HANGXUAT VALUES
('HD01', 'VT01', 700000, 50),
('HD01', 'VT02', 5500, 30),
('HD02', 'VT01', 700000, 100),
('HD02', 'VT02', 5500, 40);


-- CAU 2 --
SELECT TOP 1
MAHD, SUM(SLBAN * DONGIA) AS N'Tổng Tiền'
FROM HANGXUAT
GROUP BY MAHD
ORDER BY SUM(SLBAN * DONGIA) Desc;

-- CAU 3 --
GO
CREATE FUNCTION NGAY (@NGAY DATETIME)
RETURNS NVARCHAR(100)
AS
BEGIN
    DECLARE @SONGAY INT;
	SET @SONGAY = DATEPART(WEEKDAY, @NGAY)
	DECLARE @THU NVARCHAR(100);

	IF (@SONGAY =0)
	BEGIN
	   SET @THU ='THU 2'
	END
	IF (@SONGAY =1)
	BEGIN
	   SET @THU ='THU 3'
	END
	IF (@SONGAY =2)
	BEGIN
	   SET @THU ='THU 4'
	END
	IF (@SONGAY =3)
	BEGIN
	   SET @THU ='THU 5'
	END
	IF (@SONGAY =4)
	BEGIN
	   SET @THU ='THU 6'
	END
	IF (@SONGAY =5)
	BEGIN
	   SET @THU ='THU 7'
	END
	IF (@SONGAY =6)
	BEGIN
	   SET @THU ='CHU NHAT'
	END
	RETURN @THU
END
GO
CREATE FUNCTION HAMC3(@MAHD INT)
RETURNS TABLE
AS
  RETURN
     SELECT dbo.HDBAN.MAHD,NGAYXUAT,MAVT,DONGIA,SLBAN,dbo.C3(NGAYXUAT) AS 'NGAYTHU'
	 FROM dbo.HANGXUAT, dbo.HDBAN
	 WHERE dbo.HDBAN.MAHD = dbo.HANGXUAT.MAHD AND
	 dbo.HANGXUAT.MAHD= @MAHD
GO


-- CAU 4 --
GO
CREATE PROCEDURE p4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;